//! End-to-end tests for the `file` output: the config, the connection, the
//! `--data-dir` sandbox and the bytes that end up on disk.
//!
//! The pieces have their own unit tests — path resolution in
//! `outputs::file::tests`, rotation and encoding in `outputs::rotate::tests`.
//! What is tested here is the *wiring*, which none of those can reach: that a
//! config naming a connection reaches a real directory, that the sandbox is
//! actually consulted on the path a build takes, and that a run produces files
//! a reader can parse.
//!
//! Everything writes into a `tempfile::TempDir`, so the suite still needs no
//! network, no server and no fixture directory.

use kayak::outputs::BuildOutput;
use kayak::state::{AppState, PipelineId, UiEvent};
use kayak::testing::batch;
use kayak::{BuildCtx, outputs::OutputDestination};
use kayak_core::config::FileOutputConfig;
use kayak_core::connections::{ConnectionKind, Connections, FileConnection};
use serde_json::{Value, json};
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::sync::broadcast;

/// A sandbox with a `local-files` connection rooted inside it.
struct Fixture {
    _directory: tempfile::TempDir,
    data_dir: PathBuf,
    connections: Arc<Connections>,
}

fn fixture() -> anyhow::Result<Fixture> {
    fixture_rooted_at(None)
}

/// As [`fixture`], with the connection's root pointed somewhere else — which is
/// how the "root outside the sandbox" case is set up.
fn fixture_rooted_at(root: Option<&Path>) -> anyhow::Result<Fixture> {
    let directory = tempfile::tempdir()?;
    let data_dir = std::fs::canonicalize(directory.path())?;
    let root = root.map_or_else(|| data_dir.join("events"), Path::to_path_buf);
    let connections = [(
        "local-files".to_string(),
        ConnectionKind::File(FileConnection {
            root: root.to_string_lossy().into_owned(),
        }),
    )]
    .into_iter()
    .collect();
    Ok(Fixture {
        _directory: directory,
        data_dir,
        connections: Arc::new(connections),
    })
}

/// Build the output the way a pipeline would — through the config, the
/// connection and the data dir, rather than by constructing it directly.
fn build(
    fixture: &Fixture,
    config: Value,
    data_dir: Option<&Path>,
) -> anyhow::Result<Box<dyn OutputDestination>> {
    let config: FileOutputConfig = serde_json::from_value(config)?;
    let mut pipelines = HashMap::new();
    let (events, _) = broadcast::channel::<UiEvent>(16);
    let mut ctx = BuildCtx::new(&mut pipelines, PipelineId::from("p1"), events)
        .with_connections(Arc::clone(&fixture.connections))
        .with_data_dir(data_dir.map(|dir| Arc::new(dir.to_path_buf())));
    config.build(&mut ctx)
}

/// Every file written under `directory`, in name order — which is the order
/// they were written in, since that is what the naming scheme guarantees.
fn parts(directory: &Path) -> anyhow::Result<Vec<(String, String)>> {
    let mut parts = Vec::new();
    for entry in std::fs::read_dir(directory)? {
        let entry = entry?;
        parts.push((
            entry.file_name().to_string_lossy().into_owned(),
            std::fs::read_to_string(entry.path())?,
        ));
    }
    parts.sort();
    Ok(parts)
}

/// The extension a part was written under. Compared exactly rather than
/// case-insensitively: this name is generated by the output, not read off a
/// disk someone else wrote to, so a difference in case would be a real change.
fn extension(name: &str) -> Option<&str> {
    Path::new(name)
        .extension()
        .and_then(std::ffi::OsStr::to_str)
}

fn ndjson(config: Value) -> Value {
    let mut config = config;
    if let Some(object) = config.as_object_mut() {
        object.insert("type".into(), json!("file"));
        object.insert("connection".into(), json!("local-files"));
    }
    config
}

#[tokio::test]
async fn a_batch_is_written_as_one_json_message_per_line() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let mut output = build(
        &fixture,
        ndjson(json!({"path": "orders"})),
        Some(&fixture.data_dir),
    )?;
    output.init().await?;
    output
        .emit(batch(vec![json!({"id": 1}), json!({"id": 2})]))
        .await?;

    let written = parts(&fixture.data_dir.join("events").join("orders"))?;
    assert_eq!(written.len(), 1, "one batch, one part: {written:?}");
    let (name, contents) = &written[0];
    assert_eq!(extension(name), Some("ndjson"), "{name}");
    let ids: Vec<Value> = contents
        .lines()
        .map(serde_json::from_str)
        .collect::<Result<_, _>>()?;
    assert_eq!(ids, vec![json!({"id": 1}), json!({"id": 2})]);
    Ok(())
}

/// The directory is created by the build, so a pipeline does not fail at
/// runtime over a `mkdir` nobody was told to run.
#[tokio::test]
async fn building_creates_the_directory() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let nested = fixture.data_dir.join("events").join("orders").join("eu");
    assert!(!nested.exists());
    let _output = build(
        &fixture,
        ndjson(json!({"path": "orders/eu"})),
        Some(&fixture.data_dir),
    )?;
    assert!(nested.is_dir());
    Ok(())
}

/// Nothing arrived, so nothing is written — an empty file per idle pipeline
/// would be noise a reader has to filter out.
#[tokio::test]
async fn a_pipeline_that_emits_nothing_writes_no_file() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let mut output = build(
        &fixture,
        ndjson(json!({"path": "orders"})),
        Some(&fixture.data_dir),
    )?;
    output.init().await?;
    output.emit(batch(vec![])).await?;

    assert!(parts(&fixture.data_dir.join("events").join("orders"))?.is_empty());
    Ok(())
}

#[tokio::test]
async fn a_row_limit_starts_a_new_part() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let mut output = build(
        &fixture,
        ndjson(json!({"path": "orders", "rotate": {"max_rows": 2}})),
        Some(&fixture.data_dir),
    )?;
    output.init().await?;
    for id in 0..6 {
        output.emit(batch(vec![json!({"id": id})])).await?;
    }

    let written = parts(&fixture.data_dir.join("events").join("orders"))?;
    assert_eq!(written.len(), 3, "six messages, two per part: {written:?}");
    for (name, contents) in &written {
        assert_eq!(contents.lines().count(), 2, "{name}");
    }
    // and between them they hold every message exactly once, in order
    let ids: Vec<Value> = written
        .iter()
        .flat_map(|(_, contents)| contents.lines())
        .map(serde_json::from_str)
        .collect::<Result<_, _>>()?;
    assert_eq!(ids.len(), 6);
    assert_eq!(ids[0], json!({"id": 0}));
    assert_eq!(ids[5], json!({"id": 5}));
    Ok(())
}

/// Rotation is checked after the write, so the part that tips the limit is
/// oversized rather than the batch being torn in half. A message is a record
/// and must not be split across two files.
#[tokio::test]
async fn a_batch_is_never_split_across_two_parts() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let mut output = build(
        &fixture,
        ndjson(json!({"path": "orders", "rotate": {"max_rows": 2}})),
        Some(&fixture.data_dir),
    )?;
    output.init().await?;
    output
        .emit(batch((0..5).map(|id| json!({"id": id})).collect()))
        .await?;

    let written = parts(&fixture.data_dir.join("events").join("orders"))?;
    assert_eq!(written.len(), 1, "the batch stayed together: {written:?}");
    assert_eq!(written[0].1.lines().count(), 5);
    Ok(())
}

#[tokio::test]
async fn a_json_array_part_is_closed_when_it_rotates() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let mut output = build(
        &fixture,
        ndjson(json!({
            "path": "orders",
            "format": "json_array",
            "rotate": {"max_rows": 2}
        })),
        Some(&fixture.data_dir),
    )?;
    output.init().await?;
    for id in 0..4 {
        output.emit(batch(vec![json!({"id": id})])).await?;
    }

    let written = parts(&fixture.data_dir.join("events").join("orders"))?;
    assert_eq!(written.len(), 2);
    for (name, contents) in &written {
        assert_eq!(extension(name), Some("json"), "{name}");
        let messages: Vec<Value> = serde_json::from_str(contents)?;
        assert_eq!(messages.len(), 2, "{name}: {contents}");
    }
    Ok(())
}

/// The closed default, at the layer that matters: a config can be perfectly
/// valid and still not build, because the *server* was never told it may write.
#[tokio::test]
async fn without_a_data_dir_a_file_output_refuses_to_build() -> anyhow::Result<()> {
    let fixture = fixture()?;
    let Err(err) = build(&fixture, ndjson(json!({"path": "orders"})), None) else {
        panic!("a file output built on a server started without --data-dir");
    };
    assert!(format!("{err:#}").contains("--data-dir"), "{err:#}");
    Ok(())
}

/// A connection arrives over HTTP like anything else, so its root is checked
/// rather than trusted — this is the case that makes `--data-dir` a boundary
/// instead of a default.
#[tokio::test]
async fn a_connection_rooted_outside_the_data_dir_refuses_to_build() -> anyhow::Result<()> {
    let outside = tempfile::tempdir()?;
    let fixture = fixture_rooted_at(Some(outside.path()))?;
    let Err(err) = build(
        &fixture,
        ndjson(json!({"path": "orders"})),
        Some(&fixture.data_dir),
    ) else {
        panic!("a connection rooted outside the data dir was accepted");
    };
    assert!(format!("{err:#}").contains("--data-dir"), "{err:#}");
    assert!(!outside.path().join("orders").exists());
    Ok(())
}

/// Refused, not trimmed — and refused *before* anything is created, so a
/// rejected path leaves nothing behind.
#[tokio::test]
async fn a_path_escaping_the_root_refuses_to_build() -> anyhow::Result<()> {
    let fixture = fixture()?;
    for path in ["../escaped", "orders/../../escaped", "/etc/kayak"] {
        let Err(err) = build(
            &fixture,
            ndjson(json!({ "path": path })),
            Some(&fixture.data_dir),
        ) else {
            panic!("'{path}' was accepted");
        };
        assert!(
            format!("{err:#}").contains("file output cannot write"),
            "{path}: {err:#}"
        );
    }
    assert!(!fixture.data_dir.join("escaped").exists());
    Ok(())
}

/// The kind is checked as well as the name, the same way every other component
/// checks it — a nats server is not a directory.
#[tokio::test]
async fn naming_a_connection_of_the_wrong_kind_refuses_to_build() -> anyhow::Result<()> {
    let directory = tempfile::tempdir()?;
    let data_dir = std::fs::canonicalize(directory.path())?;
    let connections: Connections = [(
        "local-files".to_string(),
        ConnectionKind::Nats(kayak_core::connections::NatsConnection {
            urls: "nats://localhost:4222".into(),
        }),
    )]
    .into_iter()
    .collect();
    let fixture = Fixture {
        _directory: directory,
        data_dir,
        connections: Arc::new(connections),
    };

    let Err(err) = build(
        &fixture,
        ndjson(json!({"path": "orders"})),
        Some(&fixture.data_dir),
    ) else {
        panic!("a nats connection was accepted as a file one");
    };
    assert!(format!("{err:#}").contains("nats connection"), "{err:#}");
    Ok(())
}

/// A file output names a connection, so the graph has to report it — that is
/// what "is this connection still in use" is answered from, and a connection
/// deleted out from under a running file output would be a silent hole.
#[test]
fn a_file_output_reports_the_connection_it_uses() -> anyhow::Result<()> {
    let config: kayak_core::config::Config = serde_json::from_value(json!({
        "id": "p1",
        "inputs": [{"type": "dummy", "duration": 3600}],
        "transforms": [],
        "outputs": [{
            "type": "file",
            "connection": "local-files",
            "path": "orders"
        }]
    }))?;
    assert_eq!(config.connections(), vec!["local-files"]);
    Ok(())
}

/// The whole path a real server takes: a config file on disk, the connections
/// beside it, and `--data-dir` supplied at startup. The builder that sets a
/// data dir afterwards would be too late here — loading a config *starts* its
/// pipelines — so this is what pins the parameter being on the constructor.
#[tokio::test]
async fn a_server_started_with_a_data_dir_starts_a_file_pipeline_from_its_config()
-> anyhow::Result<()> {
    let directory = tempfile::tempdir()?;
    let data_dir = std::fs::canonicalize(directory.path())?;
    let config_path = data_dir.join("config.json");
    std::fs::write(
        &config_path,
        serde_json::to_string_pretty(&json!([{
            "id": "to-disk",
            "inputs": [{"type": "dummy", "duration": 3600}],
            "transforms": [],
            "outputs": [{
                "type": "file",
                "connection": "local-files",
                "path": "orders"
            }]
        }]))?,
    )?;
    std::fs::write(
        data_dir.join("config.connections.json"),
        serde_json::to_string_pretty(&json!({
            "local-files": {"type": "file", "root": data_dir.join("events")}
        }))?,
    )?;

    let state = AppState::from_config_with(
        &config_path,
        Arc::new(kayak::secrets::EnvStore),
        None,
        Some(data_dir.clone()),
    )?;
    assert_eq!(state.get_pipeline_ids(), vec!["to-disk".to_string()]);
    // the build created the directory it will write into
    assert!(data_dir.join("events").join("orders").is_dir());
    Ok(())
}

/// ...and the same config on a server without the flag does not start. The
/// failure has to be loud: a file output that silently did nothing would look
/// like a working pipeline losing data.
#[tokio::test]
async fn the_same_config_without_a_data_dir_does_not_start() -> anyhow::Result<()> {
    let directory = tempfile::tempdir()?;
    let data_dir = std::fs::canonicalize(directory.path())?;
    let config_path = data_dir.join("config.json");
    std::fs::write(
        &config_path,
        serde_json::to_string_pretty(&json!([{
            "id": "to-disk",
            "inputs": [{"type": "dummy", "duration": 3600}],
            "transforms": [],
            "outputs": [{
                "type": "file",
                "connection": "local-files",
                "path": "orders"
            }]
        }]))?,
    )?;
    std::fs::write(
        data_dir.join("config.connections.json"),
        serde_json::to_string_pretty(&json!({
            "local-files": {"type": "file", "root": data_dir.join("events")}
        }))?,
    )?;

    let started =
        AppState::from_config_with(&config_path, Arc::new(kayak::secrets::EnvStore), None, None);
    assert!(
        started.is_err(),
        "a file pipeline started on a server with no --data-dir"
    );
    Ok(())
}
