//! The doc site's reference, rendered out of the same reflection the UI uses.
//!
//! `website/` is a `VitePress` site whose prose is written by hand and whose
//! reference tables are not written at all. Everything under
//! `website/reference/generated/` comes from here: the component tables are
//! [`kayak_core::docs`] (which reflects the config schemas, so the doc comments
//! on the config structs *are* the docs), the HTTP tables are
//! [`kayak_core::api_docs`] (the same table `api_router` is folded over), and
//! `openapi.json` is [`kayak::openapi::document`]. Nothing here knows the name
//! of any component or endpoint, exactly as `docs.rs` doesn't — a component
//! added to the config enums appears on the site with no edit here and none in
//! `website/`.
//!
//! The generated files are **markdown partials**, not pages: they carry no
//! title and no front matter, and a prose page pulls one in with
//! `VitePress`' `<!--@include: -->`. That is the whole anti-duplication argument — the site
//! owns the narrative and the ordering, this owns every table, and neither
//! restates the other. A page can include a family whole (so a new component
//! turns up without an edit) or include components one at a time with prose
//! between them.
//!
//! This module is pure: [`files`] returns what should be on disk, `main.rs`
//! writes it, and `tests/up_to_date.rs` compares it against what is committed —
//! which is what makes a stale site a failing test rather than a surprise.

// Every string here is assembled by appending, at build time, once per file.
// `format!` into `push_str` is the readable spelling of that, and the one
// allocation it costs per row is not worth a `write!` whose `Result` can never
// be an error.
#![allow(clippy::format_push_string)]

use kayak_core::api_docs::{ApiDoc, Body, TAGS, endpoints, schemas};
use kayak_core::docs::{
    ComponentDoc, Family, FieldDoc, FieldType, StateDoc, all_components, state_docs,
};
use serde_json::{Value, json};

/// Where generated partials live, relative to the site root.
pub const GENERATED: &str = "reference/generated";

/// The line every generated file opens with. It is an HTML comment, so it
/// renders as nothing and reads as a warning in an editor.
const BANNER: &str =
    "<!-- generated by `just docs` from kayak's config schemas and endpoint table. do not edit. -->";

/// One file the site expects to find, and what should be in it.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to the site root (`website/`), always with `/` separators.
    pub path: String,
    pub contents: String,
}

/// Everything the generator produces, in a stable order.
#[must_use]
pub fn files() -> Vec<GeneratedFile> {
    let components = all_components();
    let mut out = Vec::new();

    for family in [
        Family::Input,
        Family::Transform,
        Family::Output,
        Family::Connection,
    ] {
        let of_family: Vec<&ComponentDoc> =
            components.iter().filter(|c| c.family == family).collect();

        for component in &of_family {
            out.push(GeneratedFile {
                path: format!(
                    "{GENERATED}/components/{}/{}.md",
                    family.label(),
                    component.kind
                ),
                contents: partial(&component_section(component)),
            });
        }

        let whole = of_family
            .iter()
            .map(|c| component_section(c))
            .collect::<Vec<_>>()
            .join("\n");
        out.push(GeneratedFile {
            path: format!("{GENERATED}/components/{}.md", family.label()),
            contents: partial(&whole),
        });
    }

    out.push(GeneratedFile {
        path: format!("{GENERATED}/state.md"),
        contents: partial(&state_sections(&state_docs())),
    });

    let api = endpoints();
    out.push(GeneratedFile {
        path: format!("{GENERATED}/api/endpoints.md"),
        contents: partial(&api_sections(&api)),
    });
    out.push(GeneratedFile {
        path: format!("{GENERATED}/api/schemas.md"),
        contents: partial(&schema_sections()),
    });

    out.push(GeneratedFile {
        path: ".vitepress/generated/sidebar.json".to_string(),
        contents: pretty_json(&sidebar(&components, &api)),
    });
    out.push(GeneratedFile {
        path: "public/openapi.json".to_string(),
        contents: pretty_json(&kayak::openapi::document()),
    });

    out
}

/// A generated partial: the banner, then the body, then exactly one newline.
fn partial(body: &str) -> String {
    format!("{BANNER}\n\n{}\n", body.trim_end())
}

fn pretty_json(value: &Value) -> String {
    let rendered = serde_json::to_string_pretty(value).unwrap_or_else(|_| "{}".to_string());
    format!("{rendered}\n")
}

// ---------------------------------------------------------------- components

/// One component, as the reference shows it: what it is, then what it takes.
fn component_section(component: &ComponentDoc) -> String {
    let mut out = format!(
        "## `{}` {{#{}}}\n\n",
        component.kind,
        component_anchor(component)
    );

    if let Some(description) = &component.description {
        out.push_str(&paragraphs(description));
    }

    if component.variants.is_empty() {
        out.push_str(&field_table(&component.fields));
        out.push_str(&nested(&component.fields));
    } else {
        // an enum-shaped component — the `filter` transform. Its fields live on
        // the variants, and the variant is *externally* tagged: it is a key
        // beside the component's own `type`, holding the fields as its value.
        // Spelling that out is the whole point of the header, so don't shorten
        // it to the variant's name.
        for variant in &component.variants {
            out.push_str(&format!(
                "**`{{\"type\": \"{}\", \"{}\": {{ … }}}}`**\n\n",
                component.kind, variant.name
            ));
            out.push_str(&field_table(&variant.fields));
            out.push_str(&nested(&variant.fields));
        }
    }

    if !component.metadata.is_empty() {
        out.push_str(
            "**metadata** — what this input attaches to a message when its `envelope` is set.\n\n",
        );
        out.push_str("| field | holds |\n| --- | --- |\n");
        for field in &component.metadata {
            out.push_str(&format!(
                "| `{}` | {} |\n",
                field.name,
                cell(&field.description)
            ));
        }
        out.push('\n');
    }

    out
}

/// The anchor a component's section carries. Family-qualified because `http` is
/// an input, a transform and an output, and a link to one must not land on
/// another if the pages are ever rearranged.
#[must_use]
pub fn component_anchor(component: &ComponentDoc) -> String {
    format!(
        "{}-{}",
        family_singular(component.family),
        component.kind.replace('_', "-")
    )
}

fn family_singular(family: Family) -> &'static str {
    match family {
        Family::Input => "input",
        Family::Transform => "transform",
        Family::Output => "output",
        Family::Connection => "connection",
    }
}

fn field_table(fields: &[FieldDoc]) -> String {
    if fields.is_empty() {
        return "This component takes no configuration.\n\n".to_string();
    }
    let mut out = String::from("| field | type | | description |\n| --- | --- | --- | --- |\n");
    for field in fields {
        out.push_str(&format!(
            "| `{}` | {} | {} | {} |\n",
            field.name,
            type_cell(field),
            requirement(field.required),
            field
                .description
                .as_deref()
                .map_or_else(String::new, cell),
        ));
    }
    out.push('\n');
    out
}

/// Whether a field has to be there, as a badge rather than as a word. A badge
/// because it is the one column that is a flag rather than prose — and because
/// styling it by its *position* would reach the description column of every
/// three-column table on the site.
fn requirement(required: bool) -> &'static str {
    if required {
        "<Badge type=\"warning\" text=\"required\" />"
    } else {
        "<Badge type=\"info\" text=\"optional\" />"
    }
}

/// How a field's type reads in a table. A closed set is spelled out rather than
/// named, and a connection says which kind it wants — both of those are the
/// answer someone reading the table actually needs.
fn type_cell(field: &FieldDoc) -> String {
    match &field.field_type {
        FieldType::Enum(values) => values
            .iter()
            .map(|v| format!("`{v}`"))
            .collect::<Vec<_>>()
            .join(" \\| "),
        FieldType::Connection(kind) => format!("`{kind}` connection"),
        FieldType::PipelineId => "pipeline id".to_string(),
        _ => format!("`{}`", cell(&field.type_name)),
    }
}

/// The tables under the table: the fields of a field that has a shape of its
/// own. `/docs` in the app renders one flat table per component and leaves
/// these to the doc comment; here there is room, so they are written out.
fn nested(fields: &[FieldDoc]) -> String {
    let mut out = String::new();
    for field in fields {
        out.push_str(&nested_field(&format!("`{}`", field.name), field));
    }
    out
}

fn nested_field(path: &str, field: &FieldDoc) -> String {
    match &field.field_type {
        FieldType::Object(inner) => {
            let mut out = format!("**{path}**\n\n{}", field_table(inner));
            out.push_str(&nested_of(path, inner));
            out
        }
        FieldType::Union(union) => {
            let mut out = String::new();
            for variant in &union.variants {
                out.push_str(&format!(
                    "**{path} — `{}: \"{}\"`**\n\n{}",
                    union.tag,
                    variant.name,
                    field_table(&variant.fields)
                ));
                out.push_str(&nested_of(path, &variant.fields));
            }
            out
        }
        FieldType::List(element) => nested_field(&format!("{path} — each entry"), element),
        _ => String::new(),
    }
}

fn nested_of(path: &str, fields: &[FieldDoc]) -> String {
    let mut out = String::new();
    for field in fields {
        out.push_str(&nested_field(&format!("{path}.`{}`", field.name), field));
    }
    out
}

// --------------------------------------------------------------------- state

fn state_sections(docs: &[StateDoc]) -> String {
    let mut out = String::new();
    for doc in docs {
        out.push_str(&format!(
            "## {} {{#{}}}\n\n`{}`\n\n",
            doc.title,
            slug(&doc.path),
            doc.path
        ));
        if let Some(description) = &doc.description {
            out.push_str(&paragraphs(description));
        }
        out.push_str(&field_table(&doc.fields));
        out.push_str(&nested(&doc.fields));
    }
    out
}

// ----------------------------------------------------------------- http api

fn api_sections(api: &[ApiDoc]) -> String {
    let mut out = String::new();
    for tag in TAGS {
        let of_tag: Vec<&ApiDoc> = api.iter().filter(|e| e.tag == tag).collect();
        if of_tag.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "## {} {{#tag-{}}}\n\n{}\n\n",
            tag.label(),
            tag.label(),
            tag.description()
        ));
        for endpoint in of_tag {
            out.push_str(&endpoint_section(endpoint));
        }
    }
    out
}

fn endpoint_section(endpoint: &ApiDoc) -> String {
    let mut out = format!(
        "### `{} {}` {{#{}}}\n\n{}\n\n",
        endpoint.method.label(),
        endpoint.path,
        endpoint.anchor_id(),
        endpoint.summary,
    );
    out.push_str(&format!(
        "<Badge type=\"{}\" text=\"{}\" /> <Badge type=\"info\" text=\"{}\" /> \
         — {}\n\n",
        if endpoint.access.is_protected() {
            "warning"
        } else {
            "tip"
        },
        endpoint.access.label(),
        endpoint.operation_id(),
        endpoint.access.description(),
    ));
    out.push_str(&paragraphs(endpoint.description));

    if !endpoint.params.is_empty() {
        out.push_str("**path parameters**\n\n| name | description |\n| --- | --- |\n");
        for param in &endpoint.params {
            out.push_str(&format!(
                "| `{}` | {} |\n",
                param.name,
                cell(param.description)
            ));
        }
        out.push('\n');
    }

    if !endpoint.query.is_empty() {
        out.push_str(
            "**query parameters** — all optional, so a bare request to this path is a \
             working request.\n\n| name | description |\n| --- | --- |\n",
        );
        for param in &endpoint.query {
            out.push_str(&format!(
                "| `{}` | {} |\n",
                param.name,
                cell(param.description)
            ));
        }
        out.push('\n');
    }

    if let Some(request) = &endpoint.request {
        out.push_str(&format!(
            "**request body** — {} {}\n\n",
            body_cell(request.body),
            cell(request.description)
        ));
    }

    out.push_str("**responses**\n\n| status | body | description |\n| --- | --- | --- |\n");
    for response in &endpoint.responses {
        out.push_str(&format!(
            "| `{}` | {} | {} |\n",
            response.status,
            body_cell(response.body),
            cell(response.description)
        ));
    }
    out.push('\n');
    out
}

/// A body, linked to its schema where it names one — the schema tables are on
/// the same page, so the link is what makes them worth generating.
fn body_cell(body: Body) -> String {
    match body.schema_name() {
        Some(name) => match body {
            Body::JsonArray(_) => format!("[[{name}](#schema-{})]", anchor_of(name)),
            _ => format!("[{name}](#schema-{})", anchor_of(name)),
        },
        None => cell(&body.type_name()),
    }
}

fn schema_sections() -> String {
    let mut out = String::from(
        "Every request and response body the endpoints above name, as JSON Schema \
         generated from the Rust types they deserialize into.\n\n",
    );
    for (name, schema) in schemas() {
        out.push_str(&format!(
            "## `{name}` {{#schema-{}}}\n\n",
            anchor_of(name)
        ));
        if let Some(description) = schema["description"].as_str() {
            out.push_str(&paragraphs(description));
        }
        out.push_str("::: details schema\n\n```json\n");
        out.push_str(&pretty_json(&schema));
        out.push_str("```\n\n:::\n\n");
    }
    out
}

/// A path or a title as an anchor: everything that isn't a letter or a digit
/// becomes a hyphen, which is both what markdown-it would have done and what
/// keeps a `<name>` placeholder out of the HTML — Vue compiles these pages, and
/// an unclosed `<name>` is a build error rather than a stray angle bracket.
fn slug(text: &str) -> String {
    let mut out = String::new();
    for ch in text.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_lowercase());
        } else if !out.ends_with('-') {
            out.push('-');
        }
    }
    out.trim_matches('-').to_string()
}

/// A schema name as an anchor: `PipelineDto` is `pipelinedto`, which is what
/// markdown-it would have made of it anyway.
fn anchor_of(name: &str) -> String {
    name.to_lowercase()
}

// ------------------------------------------------------------------ sidebar

/// The sidebar entries the site's config imports. Generated for the same reason
/// the tables are: a component added to the config enums has to appear in the
/// navigation, and remembering to add it there by hand is the kind of thing
/// nobody remembers.
fn sidebar(components: &[ComponentDoc], api: &[ApiDoc]) -> Value {
    let family_items = |family: Family| -> Value {
        components
            .iter()
            .filter(|c| c.family == family)
            .map(|c| {
                json!({
                    "text": c.kind,
                    "link": format!("/reference/{}#{}", family.label(), component_anchor(c)),
                })
            })
            .collect()
    };

    let tags: Value = TAGS
        .iter()
        .filter(|tag| api.iter().any(|e| e.tag == **tag))
        .map(|tag| {
            json!({
                "text": tag.label(),
                "link": format!("/reference/api#tag-{}", tag.label()),
            })
        })
        .collect();

    json!({
        "inputs": family_items(Family::Input),
        "transforms": family_items(Family::Transform),
        "outputs": family_items(Family::Output),
        "connections": family_items(Family::Connection),
        "api": tags,
    })
}

// ----------------------------------------------------------------- markdown

/// A doc comment as prose. Doc comments here are written with blank lines
/// between paragraphs and hard-wrapped inside them, which is exactly what
/// markdown wants, so this only has to normalise the wrapping.
fn paragraphs(text: &str) -> String {
    let mut out = String::new();
    for paragraph in text.split("\n\n") {
        let joined = paragraph.split_whitespace().collect::<Vec<_>>().join(" ");
        if !joined.is_empty() {
            out.push_str(&joined);
            out.push_str("\n\n");
        }
    }
    out
}

/// The same text in a table cell: one line, and nothing that would end the
/// cell early.
fn cell(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ").replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_generated_file_carries_the_banner_and_ends_in_one_newline() {
        for file in files() {
            if std::path::Path::new(&file.path)
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("md"))
            {
                assert!(
                    file.contents.starts_with(BANNER),
                    "{} has no banner",
                    file.path
                );
            }
            assert!(file.contents.ends_with('\n'), "{}", file.path);
            assert!(!file.contents.ends_with("\n\n"), "{}", file.path);
        }
    }

    #[test]
    fn a_family_partial_holds_every_component_of_that_family() {
        let files = files();
        let inputs = files
            .iter()
            .find(|f| f.path.ends_with("components/inputs.md"))
            .map(|f| f.contents.clone())
            .unwrap_or_default();
        for component in all_components() {
            if component.family == Family::Input {
                assert!(
                    inputs.contains(&format!("## `{}`", component.kind)),
                    "the inputs partial is missing {}",
                    component.kind
                );
            }
        }
    }

    #[test]
    fn a_component_gets_a_partial_of_its_own_as_well() {
        let files = files();
        for component in all_components() {
            let path = format!(
                "{GENERATED}/components/{}/{}.md",
                component.family.label(),
                component.kind
            );
            assert!(
                files.iter().any(|f| f.path == path),
                "no partial at {path}"
            );
        }
    }

    #[test]
    fn a_cell_cannot_end_early_or_wrap() {
        assert_eq!(cell("one\ntwo  three"), "one two three");
        assert_eq!(cell("a | b"), "a \\| b");
    }

    #[test]
    fn paragraphs_unwrap_but_keep_the_breaks() {
        assert_eq!(
            paragraphs("one\nline\n\nsecond\n"),
            "one line\n\nsecond\n\n"
        );
    }

    #[test]
    fn an_enum_shaped_component_shows_where_its_variant_key_goes() {
        // `filter` is externally tagged: the variant is a key *beside* `type`,
        // not a value of it, and a header saying otherwise is a config that
        // does not parse.
        let filter = all_components()
            .into_iter()
            .find(|c| c.kind == "filter")
            .map(|c| component_section(&c))
            .unwrap_or_default();
        assert!(
            filter.contains("{\"type\": \"filter\", \"Numeric\": { … }}"),
            "{filter}"
        );
    }

    #[test]
    fn a_requirement_is_a_badge_rather_than_a_word_in_a_column() {
        // styling that column by position would reach the description column
        // of the three-column response tables.
        assert!(requirement(true).contains("required"));
        assert!(requirement(false).starts_with("<Badge"));
    }

    #[test]
    fn a_closed_set_is_spelled_out_rather_than_named() {
        let field = FieldDoc {
            name: "function".to_string(),
            type_name: "sum | avg".to_string(),
            field_type: FieldType::Enum(vec!["sum".to_string(), "avg".to_string()]),
            description: None,
            required: true,
        };
        assert_eq!(type_cell(&field), "`sum` \\| `avg`");
    }

    #[test]
    fn a_nested_field_is_written_out_rather_than_left_to_the_doc_comment() {
        // every input takes `buffer`, which is a union of three shapes — the
        // case `/docs` in the app leaves to the prose.
        let inputs = files()
            .into_iter()
            .find(|f| f.path.ends_with("components/inputs.md"))
            .map(|f| f.contents)
            .unwrap_or_default();
        assert!(inputs.contains("**`buffer` — `type: \"tumbling\"`**"), "{inputs}");
        assert!(inputs.contains("window_seconds"));
    }

    #[test]
    fn an_anchor_holds_no_angle_brackets() {
        // `state.<name>` is a path with a placeholder in it, and Vue compiles
        // these pages — an unclosed `<name>` is a build failure, not a typo.
        assert_eq!(slug("state.<name>"), "state-name");
        assert_eq!(slug("pipelines[].state"), "pipelines-state");
    }

    #[test]
    fn a_body_links_to_the_schema_it_names() {
        assert_eq!(
            body_cell(Body::JsonArray("PipelineDto")),
            "[[PipelineDto](#schema-pipelinedto)]"
        );
        assert_eq!(body_cell(Body::None), "—");
    }

    #[test]
    fn the_sidebar_names_every_component_and_every_tag() {
        let components = all_components();
        let value = sidebar(&components, &endpoints());
        let listed: usize = ["inputs", "transforms", "outputs", "connections"]
            .iter()
            .filter_map(|key| value[key].as_array().map(Vec::len))
            .sum();
        assert_eq!(listed, components.len());
        assert_eq!(value["api"].as_array().map(Vec::len), Some(TAGS.len()));
    }
}
