local-clickhouse:
  type: clickhouse
  url: http://localhost:8123
  database: kayak
  user: kayak
  password: ${CLICKHOUSE_PASSWORD}
  allow_http: true
local-files:
  type: file
  root: dev_data/events
local-kafka:
  type: kafka
  brokers: localhost:9092
local-mqtt:
  type: mqtt
  host: localhost
  port: 1883
local-nats:
  type: nats
  urls: nats://localhost:4222
local-postgres:
  type: postgres
  host: localhost
  database: kayak
  user: kayak
  password: ${POSTGRES_PASSWORD}
  port: 5432
local-redis:
  type: redis
  url: redis://localhost:6379
local-s3:
  type: s3
  bucket: events
  access_key_id: ${S3_ACCESS_KEY_ID}
  secret_access_key: ${S3_SECRET_ACCESS_KEY}
  endpoint: http://localhost:9000
  allow_http: true
